name: Maven Deploy
on: [ push ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: mvn deploy
        run: |
          mvn --batch-mode --update-snapshots deploy
